# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Workspace < Formula
  desc "CLI tool for managing multiple project workspaces"
  homepage "https://github.com/jcleira/workspace"
  version "0.0.4"
  license "MIT"

  depends_on "git" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jcleira/workspace/releases/download/v0.0.4/workspace_Darwin_x86_64.tar.gz"
      sha256 "b880a3857a35d9cb135fed31a964887130eb6ef7b7c91ff27246d1ce31bf2efe"

      def install
        bin.install "workspace"

        bash_completion.install "completions/workspace.bash" => "workspace"
        zsh_completion.install "completions/workspace.zsh" => "_workspace"
        fish_completion.install "completions/workspace.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jcleira/workspace/releases/download/v0.0.4/workspace_Darwin_arm64.tar.gz"
      sha256 "816af6c8ee10635c0bb925c0bcd2a45854de7f118092f51ab846781d29b96852"

      def install
        bin.install "workspace"

        bash_completion.install "completions/workspace.bash" => "workspace"
        zsh_completion.install "completions/workspace.zsh" => "_workspace"
        fish_completion.install "completions/workspace.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jcleira/workspace/releases/download/v0.0.4/workspace_Linux_x86_64.tar.gz"
      sha256 "216538b584b00ef08e4b9bff56e430ce4b5d72799b3bcd1b10a2e508024fa59b"
      def install
        bin.install "workspace"

        bash_completion.install "completions/workspace.bash" => "workspace"
        zsh_completion.install "completions/workspace.zsh" => "_workspace"
        fish_completion.install "completions/workspace.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jcleira/workspace/releases/download/v0.0.4/workspace_Linux_arm64.tar.gz"
      sha256 "84778c07db59b6f7fdbc9700f3da17be85ef35a11a73493af5f5ea3bd91ad4d3"
      def install
        bin.install "workspace"

        bash_completion.install "completions/workspace.bash" => "workspace"
        zsh_completion.install "completions/workspace.zsh" => "_workspace"
        fish_completion.install "completions/workspace.fish"
      end
    end
  end

  test do
    system "#{bin}/workspace", "--version"
  end
end
