# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Workspace < Formula
  desc "CLI tool for managing multiple project workspaces"
  homepage "https://github.com/jcleira/workspace"
  version "0.0.3"
  license "MIT"

  depends_on "git" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jcleira/workspace/releases/download/v0.0.3/workspace_Darwin_x86_64.tar.gz"
      sha256 "f6a3e7fadfa0d90dad688356f33da4a59e56a63ae0003e45ed8ebc4216bb9a69"

      def install
        bin.install "workspace"

        bash_completion.install "completions/workspace.bash" => "workspace"
        zsh_completion.install "completions/workspace.zsh" => "_workspace"
        fish_completion.install "completions/workspace.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jcleira/workspace/releases/download/v0.0.3/workspace_Darwin_arm64.tar.gz"
      sha256 "e17546ed68111a679c0bb812cd4e08db8cd78a31d143566d78b0a8923e4c6aa3"

      def install
        bin.install "workspace"

        bash_completion.install "completions/workspace.bash" => "workspace"
        zsh_completion.install "completions/workspace.zsh" => "_workspace"
        fish_completion.install "completions/workspace.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jcleira/workspace/releases/download/v0.0.3/workspace_Linux_x86_64.tar.gz"
      sha256 "acf79a1f22cc407473837b90432b11964f893570e7f768e47475545c2ff3f878"
      def install
        bin.install "workspace"

        bash_completion.install "completions/workspace.bash" => "workspace"
        zsh_completion.install "completions/workspace.zsh" => "_workspace"
        fish_completion.install "completions/workspace.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jcleira/workspace/releases/download/v0.0.3/workspace_Linux_arm64.tar.gz"
      sha256 "b8a87d6cbcb341c7360b78b9b5b7639ca728ba8fefc46ad2666a1b51c00a6c10"
      def install
        bin.install "workspace"

        bash_completion.install "completions/workspace.bash" => "workspace"
        zsh_completion.install "completions/workspace.zsh" => "_workspace"
        fish_completion.install "completions/workspace.fish"
      end
    end
  end

  test do
    system "#{bin}/workspace", "--version"
  end
end
