# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Workspace < Formula
  desc "CLI tool for managing multiple project workspaces"
  homepage "https://github.com/jcleira/workspace"
  version "0.0.5"
  license "MIT"

  depends_on "git" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jcleira/workspace/releases/download/v0.0.5/workspace_Darwin_x86_64.tar.gz"
      sha256 "21540bf38be69776fa181f162dcf49dbcc53b5317954be78577d14bd7787d703"

      def install
        bin.install "workspace"

        bash_completion.install "completions/workspace.bash" => "workspace"
        zsh_completion.install "completions/workspace.zsh" => "_workspace"
        fish_completion.install "completions/workspace.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jcleira/workspace/releases/download/v0.0.5/workspace_Darwin_arm64.tar.gz"
      sha256 "601d0b1d748b3191c0f14da3b4cbb34d918d65147d7a618d0ad200c2eaae1c4b"

      def install
        bin.install "workspace"

        bash_completion.install "completions/workspace.bash" => "workspace"
        zsh_completion.install "completions/workspace.zsh" => "_workspace"
        fish_completion.install "completions/workspace.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jcleira/workspace/releases/download/v0.0.5/workspace_Linux_x86_64.tar.gz"
      sha256 "6f365eb94f1670a67615bbcc565d2bea59afbc72c6d5aee2e3d5780d6b250e37"
      def install
        bin.install "workspace"

        bash_completion.install "completions/workspace.bash" => "workspace"
        zsh_completion.install "completions/workspace.zsh" => "_workspace"
        fish_completion.install "completions/workspace.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jcleira/workspace/releases/download/v0.0.5/workspace_Linux_arm64.tar.gz"
      sha256 "9c2d98e2b68b7c4451e21530a3c5dbb6d42dbaed5f7a9d80f6b6eb66f2215bea"
      def install
        bin.install "workspace"

        bash_completion.install "completions/workspace.bash" => "workspace"
        zsh_completion.install "completions/workspace.zsh" => "_workspace"
        fish_completion.install "completions/workspace.fish"
      end
    end
  end

  test do
    system "#{bin}/workspace", "--version"
  end
end
